import{S as $,i as a}from"./assets/vendor-BrddEoy-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const S="54467062-45bd0bb5918e793a50a570a2d",E="https://pixabay.com/api/",q=15;async function p(s,t=1){const o=`${E}?key=${S}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${q}`;try{const n=await fetch(o);if(!n.ok)throw new Error(`HTTP error! status: ${n.status}`);return await n.json()}catch(n){throw console.error("Error fetching images:",n),n}}const y=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),v=new $(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const t=s.map(o=>`
    <li class="photo-card">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
      </a>
      <div class="info">
        <p>Likes: ${o.likes}</p>
        <p>Views: ${o.views}</p>
        <p>Comments: ${o.comments}</p>
        <p>Downloads: ${o.downloads}</p>
      </div>
    </li>
  `).join("");y.insertAdjacentHTML("beforeend",t),v.refresh()}function B(){y.innerHTML=""}function w(){m.style.display="inline"}function i(){m.style.display="none"}function L(){h.style.display="block"}function f(){h.style.display="none"}const b=document.querySelector(".form"),P=b.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more");let l="",c=1,d=0;b.addEventListener("submit",async s=>{if(s.preventDefault(),l=P.value.trim(),!!l){c=1,B(),f(),w();try{const t=await p(l,c);if(d=t.totalHits,t.hits.length===0){a.error({title:"No results",message:"No images found for your query"}),i();return}g(t.hits),i(),d>15&&L(),a.success({title:"Success",message:`Found ${d} images!`})}catch{i(),a.error({title:"Error",message:"Something went wrong!"})}}});M.addEventListener("click",async()=>{c+=1,w(),f();try{const s=await p(l,c);g(s.hits),i();const t=document.querySelector(".gallery .photo-card");if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}c*15>=d?(f(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):L()}catch{i(),a.error({title:"Error",message:"Failed to load more images!"})}});
//# sourceMappingURL=index.js.map
